const mongoose = require('mongoose');

const Resume = new mongoose.Schema({
    username:{
        type:String,
        require:true,
        min:3,
        max:25
    },
    userId:{
        type:String,
        unique:true,
        require:true
    },
    game:{
        type:String,
        require:true 
    },
    team:{
        type:String,
        default:""
    }, 
    team_id:{
        type:String,
        default:""
    },  
    in_game_name:{ 
        type:String,
        require:true,
        min:3
    },
    in_game_id:{
        type:String,
        require:true,
    },
    role:{
        type:String,
        require:true,
        min:3
    },
    f_d:{
        type:Number,
        require:true,
    },
    curr_tier:{
        type:String,
        require:true,
        min:3
    },
    best_tier:{
        type:String,
        require:true,
        min:3
    },
    searching_team:{
        type:String,
        require:true,
        min:3
    },
    phone:{
        type:String,
        require:true,
        unique:true,
        min:3
    },
    email:{
        type:String,
        require:true,
        unique:true,
        min:3
    },
    address:{
        type:String,
        require:true,
        min:3
    },
    age:{
        type:String,
        require:true,
        min:3
    },
    profile_pic:{
        type:String,
        min:3,
        default:""
    },
    desc:{
        type:String,
        require:true,
        min:3
    },
    instagram:{
        type:String,
        require:true,
        unique:true,
        min:3
    },
    facebook:{
        type:String,
        require:true,
        unique:true,
        min:3
    },
    discord_tag:{
        type:String,
        require:true,
        unique:true,
        min:3
    }
},
{timestamps:true}); 

module.exports = mongoose.model("Resume",Resume);